import type { BomDocumentOptions, WarehouseBOM } from './types'

/**
 * Pure binary PDF generator for the Warehouse Bill of Materials (BOM) report.
 *
 * Constructs a structured, multi-page vector PDF document containing:
 * - Corporate title banner and project/zone scope metadata
 * - Key Performance Indicators (KPI) summary metrics cards
 * - Detailed mechanical installation component tables with specifications and quantities
 * - Engineering, structural, and floor anchoring compliance notes
 * - Professional layout with page budgeting and header/footer stamps
 *
 * Returns a binary byte buffer (Uint8Array / Buffer) starting with the `%PDF-` header.
 */
export async function generateWarehouseBomPdf(
  bom: WarehouseBOM,
  options: BomDocumentOptions = {},
): Promise<Uint8Array> {
  // Dynamically import PDFKit so that SSR and headless runners resolve cleanly
  const { default: PDFDocument } = await import('pdfkit/js/pdfkit.standalone')

  return new Promise<Uint8Array>((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        autoFirstPage: false,
        size: 'LETTER',
        layout: 'landscape',
        margin: 0,
        compress: false,
        info: {
          Title: options.title ?? `${bom.projectName} — Bill of Materials`,
          Author: options.author ?? 'Pascal Warehouse Digital Twin',
          Subject: options.subject ?? `Warehouse BOM Report - ${bom.scopeLabel}`,
          Keywords: (
            options.keywords ?? ['Warehouse', 'BOM', 'Logistics', 'Racking', 'Takeoff']
          ).join(', '),
          CreationDate: new Date(),
        },
      })

      const chunks: Buffer[] = []
      doc.on('data', (chunk: Buffer) => chunks.push(chunk))
      doc.on('end', () => resolve(new Uint8Array(Buffer.concat(chunks))))
      doc.on('error', (err: Error) => reject(err))

      const pageWidth = 792 // Letter landscape 11in at 72dpi
      const pageHeight = 612 // Letter landscape 8.5in at 72dpi
      const margin = 36
      const contentWidth = pageWidth - margin * 2

      let currentPageNumber = 0
      const _totalPages = 1

      function drawHeader(_isFirstPage: boolean) {
        // Top banner background
        doc.save()
        doc.rect(0, 0, pageWidth, 54).fill('#0f172a') // Slate-900

        // Title and Project Info
        doc
          .fillColor('#38bdf8')
          .font('Helvetica-Bold')
          .fontSize(13)
          .text('PASCAL DIGITAL TWIN — WAREHOUSE BILL OF MATERIALS', margin, 14, {
            lineBreak: false,
          })

        doc
          .fillColor('#94a3b8')
          .font('Helvetica')
          .fontSize(8.5)
          .text(
            `Project: ${bom.projectName}   |   Scope: ${bom.scopeLabel}   |   Date: ${bom.date}`,
            margin,
            32,
            { lineBreak: false },
          )

        const logoText = options.companyName ?? 'LOD 400 INSTALLATION REPORT'
        doc
          .fillColor('#f1f5f9')
          .font('Helvetica-Bold')
          .fontSize(9)
          .text(logoText, pageWidth - margin - 220, 20, {
            width: 220,
            align: 'right',
            lineBreak: false,
          })

        doc.restore()
      }

      function drawFooter(pageNum: number) {
        doc.save()
        doc
          .strokeColor('#cbd5e1')
          .lineWidth(0.5)
          .moveTo(margin, pageHeight - 28)
          .lineTo(pageWidth - margin, pageHeight - 28)
          .stroke()
        doc
          .fillColor('#64748b')
          .font('Helvetica')
          .fontSize(7.5)
          .text(
            'CONFIDENTIAL & PROPRIETARY — Generated by Pascal Warehouse Engine',
            margin,
            pageHeight - 20,
            { lineBreak: false },
          )
        doc
          .fillColor('#64748b')
          .font('Helvetica')
          .fontSize(7.5)
          .text(`Page ${pageNum}`, pageWidth - margin - 100, pageHeight - 20, {
            width: 100,
            align: 'right',
            lineBreak: false,
          })
        doc.restore()
      }

      function addNewPage() {
        doc.addPage({ size: 'LETTER', layout: 'landscape', margin: 0 })
        currentPageNumber++
        drawHeader(currentPageNumber === 1)
        drawFooter(currentPageNumber)
        return 68 // Initial Y position for content
      }

      let cursorY = addNewPage()

      // ── KPI Summary Cards Block (First Page) ──────────────────────────────────
      if (bom.kpis && bom.kpis.length > 0) {
        doc.save()
        const cardMargin = 8
        const cols = 4
        const cardWidth = (contentWidth - cardMargin * (cols - 1)) / cols
        const cardHeight = 44

        bom.kpis.forEach((kpi, idx) => {
          const row = Math.floor(idx / cols)
          const col = idx % cols
          const cardX = margin + col * (cardWidth + cardMargin)
          const cardY = cursorY + row * (cardHeight + 6)

          // Card container
          doc
            .roundedRect(cardX, cardY, cardWidth, cardHeight, 4)
            .fillAndStroke('#f8fafc', '#e2e8f0')

          // Value
          doc
            .fillColor('#0f172a')
            .font('Helvetica-Bold')
            .fontSize(13)
            .text(`${kpi.value}${kpi.unit ? ` ${kpi.unit}` : ''}`, cardX + 8, cardY + 8, {
              width: cardWidth - 16,
              lineBreak: false,
            })

          // Label
          doc
            .fillColor('#64748b')
            .font('Helvetica')
            .fontSize(7.5)
            .text(kpi.label, cardX + 8, cardY + 26, { width: cardWidth - 16, lineBreak: false })
        })

        const kpiRows = Math.ceil(bom.kpis.length / cols)
        cursorY += kpiRows * (cardHeight + 6) + 12
        doc.restore()
      }

      // ── Section Tables ────────────────────────────────────────────────────────
      const colWidths = {
        role: 110,
        item: 160,
        spec: 260,
        qty: 60,
        unit: 45,
        notes: 85,
      }

      for (const section of bom.sections) {
        // Check if section header fits on current page
        if (cursorY + 60 > pageHeight - 40) {
          cursorY = addNewPage()
        }

        // Section Title Header
        doc.save()
        doc.roundedRect(margin, cursorY, contentWidth, 22, 3).fill('#1e293b') // Slate-800
        doc
          .fillColor('#ffffff')
          .font('Helvetica-Bold')
          .fontSize(9.5)
          .text(
            `${section.title.toUpperCase()} (${section.items.length} line items)`,
            margin + 10,
            cursorY + 6,
            { lineBreak: false },
          )
        cursorY += 26
        doc.restore()

        // Table Header
        doc.save()
        doc.rect(margin, cursorY, contentWidth, 18).fill('#f1f5f9')
        doc.strokeColor('#cbd5e1').lineWidth(0.5).rect(margin, cursorY, contentWidth, 18).stroke()

        let hX = margin + 6
        const headers = [
          { text: 'CATEGORY / ROLE', width: colWidths.role },
          { text: 'ITEM DESCRIPTION', width: colWidths.item },
          { text: 'SPECIFICATION / DIMENSIONS', width: colWidths.spec },
          { text: 'QUANTITY', width: colWidths.qty, align: 'right' as const },
          { text: 'UNIT', width: colWidths.unit, align: 'center' as const },
          { text: 'NOTES', width: colWidths.notes },
        ]

        doc.fillColor('#334155').font('Helvetica-Bold').fontSize(7.5)
        for (const h of headers) {
          doc.text(h.text, hX, cursorY + 5, {
            width: h.width - 6,
            align: h.align ?? 'left',
            lineBreak: false,
          })
          hX += h.width
        }
        cursorY += 18
        doc.restore()

        // Table Rows
        section.items.forEach((item, rowIndex) => {
          const rowHeight = 16
          if (cursorY + rowHeight > pageHeight - 40) {
            cursorY = addNewPage()

            // Re-render table header on new page
            doc.save()
            doc.rect(margin, cursorY, contentWidth, 18).fill('#f1f5f9')
            doc
              .strokeColor('#cbd5e1')
              .lineWidth(0.5)
              .rect(margin, cursorY, contentWidth, 18)
              .stroke()
            let rx = margin + 6
            doc.fillColor('#334155').font('Helvetica-Bold').fontSize(7.5)
            for (const h of headers) {
              doc.text(h.text, rx, cursorY + 5, {
                width: h.width - 6,
                align: h.align ?? 'left',
                lineBreak: false,
              })
              rx += h.width
            }
            cursorY += 18
            doc.restore()
          }

          doc.save()
          const isEven = rowIndex % 2 === 0
          if (isEven) {
            doc.rect(margin, cursorY, contentWidth, rowHeight).fill('#fafafa')
          }
          doc
            .strokeColor('#e2e8f0')
            .lineWidth(0.5)
            .rect(margin, cursorY, contentWidth, rowHeight)
            .stroke()

          let rX = margin + 6

          // Role
          doc
            .fillColor('#475569')
            .font('Helvetica')
            .fontSize(7)
            .text(item.role, rX, cursorY + 4, { width: colWidths.role - 8, lineBreak: false })
          rX += colWidths.role

          // Item
          doc
            .fillColor('#0f172a')
            .font('Helvetica-Bold')
            .fontSize(7.5)
            .text(item.item, rX, cursorY + 4, { width: colWidths.item - 8, lineBreak: false })
          rX += colWidths.item

          // Spec
          doc
            .fillColor('#334155')
            .font('Helvetica')
            .fontSize(7)
            .text(item.specification, rX, cursorY + 4, {
              width: colWidths.spec - 8,
              lineBreak: false,
            })
          rX += colWidths.spec

          // Quantity
          doc
            .fillColor('#0f172a')
            .font('Helvetica-Bold')
            .fontSize(7.5)
            .text(item.quantity.toLocaleString(), rX, cursorY + 4, {
              width: colWidths.qty - 10,
              align: 'right',
              lineBreak: false,
            })
          rX += colWidths.qty

          // Unit
          doc
            .fillColor('#64748b')
            .font('Helvetica')
            .fontSize(7)
            .text(item.unit, rX, cursorY + 4, {
              width: colWidths.unit - 6,
              align: 'center',
              lineBreak: false,
            })
          rX += colWidths.unit

          // Notes
          doc
            .fillColor('#64748b')
            .font('Helvetica-Oblique')
            .fontSize(6.5)
            .text(item.notes ?? '', rX, cursorY + 4, {
              width: colWidths.notes - 6,
              lineBreak: false,
            })

          cursorY += rowHeight
          doc.restore()
        })

        cursorY += 12 // Spacing after section
      }

      // ── Engineering Notes Block ───────────────────────────────────────────────
      if (bom.engineeringNotes && bom.engineeringNotes.length > 0) {
        if (cursorY + 110 > pageHeight - 40) {
          cursorY = addNewPage()
        }

        doc.save()
        doc.roundedRect(margin, cursorY, contentWidth, 20, 3).fill('#334155')
        doc
          .fillColor('#ffffff')
          .font('Helvetica-Bold')
          .fontSize(8.5)
          .text(
            'STRUCTURAL COMPLIANCE & ENGINEERING INSTALLATION NOTES',
            margin + 10,
            cursorY + 5,
            { lineBreak: false },
          )
        cursorY += 24

        const notesBoxHeight = bom.engineeringNotes.length * 12 + 10
        doc
          .roundedRect(margin, cursorY, contentWidth, notesBoxHeight, 3)
          .fillAndStroke('#f8fafc', '#cbd5e1')

        bom.engineeringNotes.forEach((note, nIdx) => {
          doc
            .fillColor('#334155')
            .font('Helvetica')
            .fontSize(7)
            .text(note, margin + 10, cursorY + 6 + nIdx * 12, {
              width: contentWidth - 20,
              lineBreak: false,
            })
        })

        cursorY += notesBoxHeight + 14
        doc.restore()
      }

      doc.end()
    } catch (err) {
      reject(err)
    }
  })
}
